spring:
  application:
    name: myJavaApp

  datasource:
    url: jdbc:postgresql://localhost:5432/localJava
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update      # auto-create/update tables from your @Entity classes
    open-in-view: false

  # Needed for browser auto-refresh in Step 5.
  # In Spring Boot 4 this is OFF by default.
  devtools:
    livereload:
      enabled: true

server:
  port: 8080
